### PR TITLE
Report bug fixing issue #45

### PR DESCRIPTION
**Pull request by SyedAsherAhmed**

### CODE REVIEW

**Comment by Furqankhanzada** [comment]
@SyedAsherAhmed it shows blank page online for long time before showing report. can we show some message on ? like ```loading  .....```

**Comment by SyedAsherAhmed** [comment]
@Furqankhanzada Yes,I am working on it..

**Comment by Furqankhanzada** [comment]
@SyedAsherAhmed is loader image in use ? if not then please remove it.

**Comment by SyedAsherAhmed** [comment]
@Furqankhanzada We are not using image loader,I have removed it.

**Pull request merged**
