### PR TITLE
Register and default bank account

### PR DESCRIPTION
**Pull request by SyedAsherAhmed**

### CODE REVIEW

**Comment by Furqankhanzada** [comment]
@SyedAsherAhmed please move code to ```imports/api/auth/methods.js```

**Comment by SyedAsherAhmed** [comment]
Sign Up and Login Methods implementation in "auth" directory is done.
@Furqankhanzada

**Comment by Furqankhanzada** [comment]
@SyedAsherAhmed update this work to ES6 syntax.

**Comment by SyedAsherAhmed** [comment]
@Furqankhanzada Yes sir i am working on it..

**Comment by SyedAsherAhmed** [comment]
@Furqankhanzada SignUp and Login methods implementation through ES6 syntax is done.

**Comment by SyedAsherAhmed** [comment]
@Furqankhanzada SignUp and Login methods implementation through ES6 syntax is done.

**Pull request merged**
